### ISSUE TITLE
Scraper crash

### ISSUE THREAD

**Issue by xme** [docintelapp/DocIntel#23]
Another one:
```
2022-11-11 08:14:19.6487 [INFO] [MassTransit] Bus stopped: rabbitmq://docintel-dev-rabbitmq/
Unhandled exception. System.InvalidOperationException: Sequence contains more than one element.
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at DocIntel.Core.Services.BaseDataDbService.ApplyYourChangeAsync(IServiceProvider scopedServices) in /src/DocIntel.Core/Services/BaseDataDbService.cs:line 57
   at RunMethodsSequentially.LockAndRunCode.JobRunner.RunJobAsync(IServiceProvider scopedServices)
   at RunMethodsSequentially.LockAndRunCode.PostgreSqlLockAndRunJob.LockAndRunMethodsAsync(IServiceProvider serviceProvider)
   at RunMethodsSequentially.LockAndRunCode.PostgreSqlLockAndRunJob.LockAndRunMethodsAsync(IServiceProvider serviceProvider)
   at RunMethodsSequentially.LockAndRunCode.GetLockAndThenRunServices.LockAndLoadAsync()
   at RunMethodsSequentially.LockAndRunCode.GetLockAndThenRunHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at DocIntel.Services.Scraper.Program.Main(String[] args) in /src/DocIntel.Services.Scraper/Program.cs:line 33
```

**Comment by ancailliau** [comment]
It looks like the scraper is crashing because you have multiple users named "administrator". While it should not crash, the application should also not let you create two users with the same username...
