### ISSUE TITLE
Another strange Indexer error

### ISSUE THREAD

**Issue by xme** [docintelapp/DocIntel#28]
This error is coming at regular interval (and no more RSS feed are indexed)

```
2022-11-11 16:19:54.8512 [INFO] [DocIntel.Core.Importers.RSSSourceImporter] Source : TrendMicro
2022-11-11 16:19:55.0978 [ERROR] [DocIntel.Services.Importer.Runner] Object reference not set to an instance of an object.
   at DocIntel.Core.Importers.RSSSourceImporter.PullAsync(Nullable`1 lastPull, Int32 limit)+MoveNext() in /src/DocIntel.Core/Importers/RSSSourceImporter.cs:line 81
   at DocIntel.Core.Importers.RSSSourceImporter.PullAsync(Nullable`1 lastPull, Int32 limit)+MoveNext() in /src/DocIntel.Core/Importers/RSSSourceImporter.cs:line 83
   at DocIntel.Core.Importers.RSSSourceImporter.PullAsync(Nullable`1 lastPull, Int32 limit)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at DocIntel.Services.Importer.Runner.ImportFeeds() in /src/DocIntel.Services.Importer/Runner.cs:line 116
   at DocIntel.Services.Importer.Runner.ImportFeeds() in /src/DocIntel.Services.Importer/Runner.cs:line 116
   at DocIntel.Services.Importer.Runner.RunAsync(CancellationToken cancellationToken) in /src/DocIntel.Services.Importer/Runner.cs:line 70
```

**Comment by xme** [comment]
DtdProcessing set in appconfig.json and now:
```
2022-11-12 00:18:27.1962 [ERROR] [DocIntel.Services.Importer.Runner] The 'XmlReaderSettings.DtdProcessing' property is read only and cannot be set.
   at System.Xml.XmlReaderSettings.CheckReadOnly(String propertyName)
   at System.Xml.XmlReaderSettings.set_DtdProcessing(DtdProcessing value)
   at DocIntel.Core.Importers.RSSSourceImporter.PullAsync(Nullable`1 lastPull, Int32 limit)+MoveNext() in /src/DocIntel.Core/Importers/RSSSourceImporter.cs:line 81
   at DocIntel.Core.Importers.RSSSourceImporter.PullAsync(Nullable`1 lastPull, Int32 limit)+MoveNext() in /src/DocIntel.Core/Importers/RSSSourceImporter.cs:line 83
   at DocIntel.Core.Importers.RSSSourceImporter.PullAsync(Nullable`1 lastPull, Int32 limit)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at DocIntel.Services.Importer.Runner.ImportFeeds() in /src/DocIntel.Services.Importer/Runner.cs:line 116
   at DocIntel.Services.Importer.Runner.ImportFeeds() in /src/DocIntel.Services.Importer/Runner.cs:line 116
   at DocIntel.Services.Importer.Runner.RunAsync(CancellationToken cancellationToken) in /src/DocIntel.Services.Importer/Runner.cs:line 70
```
