### ISSUE TITLE
solr exception

### ISSUE THREAD

**Issue by xme** [docintelapp/DocIntel#31]
Here is what I saw in the logs:
```
docintel-dev-solr               | Caused by: java.lang.IllegalArgumentException: DocValuesField "title_order" appears more than once in this document (only one value is allowed per field)
docintel-dev-solr               |       at org.apache.lucene.index.SortedDocValuesWriter.addValue(SortedDocValuesWriter.java:67) ~[?:?]
docintel-dev-solr               |       at org.apache.lucene.index.IndexingChain.indexDocValue(IndexingChain.java:977) ~[?:?]
docintel-dev-solr               |       at org.apache.lucene.index.IndexingChain.processField(IndexingChain.java:758) ~[?:?]
docintel-dev-solr               |       at org.apache.lucene.index.IndexingChain.processDocument(IndexingChain.java:620) ~[?:?]
docintel-dev-solr               |       at org.apache.lucene.index.DocumentsWriterPerThread.updateDocuments(DocumentsWriterPerThread.java:239) ~[?:?]
docintel-dev-solr               |       at org.apache.lucene.index.DocumentsWriter.updateDocuments(DocumentsWriter.java:432) ~[?:?]
docintel-dev-solr               |       at org.apache.lucene.index.IndexWriter.updateDocuments(IndexWriter.java:1530) ~[?:?]
docintel-dev-solr               |       at org.apache.lucene.index.IndexWriter.updateDocuments(IndexWriter.java:1519) ~[?:?]
docintel-dev-solr               |       at org.apache.solr.update.DirectUpdateHandler2.updateDocOrDocValues(DirectUpdateHandler2.java:1046) ~[?:?]
docintel-dev-solr               |       at org.apache.solr.update.DirectUpdateHandler2.doNormalUpdate(DirectUpdateHandler2.java:416) ~[?:?]
docintel-dev-solr               |       at org.apache.solr.update.DirectUpdateHandler2.addDoc0(DirectUpdateHandler2.java:369) ~[?:?]
docintel-dev-solr               |       at org.apache.solr.update.DirectUpdateHandler2.addDoc(DirectUpdateHandler2.java:300) ~[?:?]
docintel-dev-solr               |       ... 80 more

```
Unfortunately, I don't have more context...

**Comment by brennane** [comment]
FYI here is my memo on finding it in a kubernetes deployment, with my note on using wireshark to chase down the offending document.  docker compose and docker swarm a bit of a headache.  I link to a git repo with my rancher-desktop setup (I am certainly no kubernetes certified person, but have an RKE2 HA cluster and rancher-desktop running this, apart from solr which was killing me)

https://gist.github.com/brennane/7433e7929dcb1082aff19dba67bda4c8
