### ISSUE TITLE
Importer enforces HTTPS proxy authentication

### ISSUE THREAD

**Issue by evolution536** [docintelapp/DocIntel#38]
I have DocIntel running behind a HTTPS proxy and the importer/scraper uses the configured proxy just fine. However, the importer quits immediately after starting up because it tries to log into the proxy server with apparently default user root. Actually no authentication is configured and therefore, none should be used. Do I need to configure something in addition to the http(s)_proxy variables, or is this a bug? See the error message below.

`Unhandled exception. Synsharp.SynapseException: Could not login with the user 'root'.
 ---> System.Net.Http.HttpRequestException: The proxy tunnel request to proxy 'http://REDACTED_proxy_server/' failed with status code '403'."
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Synsharp.SynapseClient.LoginAsync(String user, String password) in /src/synsharp/Synsharp/SynapseClient.cs:line 132
   --- End of inner exception stack trace ---
   at Synsharp.SynapseClient.LoginAsync(String user, String password) in /src/synsharp/Synsharp/SynapseClient.cs:line 145
   at Synsharp.SynapseClient.StormAsync[T](String query, ApiStormQueryOpts apiStormQueryOpts)+MoveNext() in /src/synsharp/Synsharp/SynapseClient.cs:line 252
   at Synsharp.SynapseClient.StormAsync[T](String query, ApiStormQueryOpts apiStormQueryOpts)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at System.Linq.AsyncEnumerable.<CountAsync>g__Core|71_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Count.cs:line 41
   at System.Linq.AsyncEnumerable.<CountAsync>g__Core|71_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Count.cs:line 41
   at DocIntel.Core.Services.InstallSynapseCustomObjects.ApplyYourChangeAsync(IServiceProvider scopedServices) in /src/DocIntel.Core/Services/InstallSynapseCustomObjects.cs:line 22
   at RunMethodsSequentially.LockAndRunCode.JobRunner.RunJobAsync(IServiceProvider scopedServices)
   at RunMethodsSequentially.LockAndRunCode.PostgreSqlLockAndRunJob.LockAndRunMethodsAsync(IServiceProvider serviceProvider)
   at RunMethodsSequentially.LockAndRunCode.PostgreSqlLockAndRunJob.LockAndRunMethodsAsync(IServiceProvider serviceProvider)
   at RunMethodsSequentially.LockAndRunCode.GetLockAndThenRunServices.LockAndLoadAsync()
   at RunMethodsSequentially.LockAndRunCode.GetLockAndThenRunHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at DocIntel.Services.Importer.Program.Main(String[] args) in /src/DocIntel.Services.Importer/Program.cs:line 33`

Thanks!

**Comment by ancailliau** [comment]
The connection to the Synapse server is not expecting to go through the proxy, or expect the proxy to forward what is needed. You should consider adding the synapse server in the the no_proxy list.

**Comment by evolution536** [comment]
That worked, thanks! As I have no idea which components communicate with each other on HTTP or HTTPS (obviously Synapse and Solr), I just did the following in docker-compose.yml:

```
x-common-variables: &common-variables
  http_proxy: REDADCTED
  https_proxy: REDACTED
  no_proxy: docintel-dev-synapse,docintel-dev-source-indexer,docintel-dev-rabbitmq,docintel-dev-document-indexer,docintel-dev-tag-indexer,docintel-dev-thumbnailer,docintel-dev-solr

services:
...
        environment: *common-variables
...
  synapse:
    environment:
      <<: *common-variables
      SYN_CORTEX_AUTH_PASSWD: REDACTED
```

And that works. However, all RSS-imported documents are still pending ingestion and nothing happens. Could you direct me in which containers I need to put on the no_proxy list for DocIntel to work completely?

Thanks again for your help! I already saw the ticket you made to improve documentation. :)

**Comment by ancailliau** [comment]
Documentation updated, to be published soon.

**Comment by orange-cert-cc** [comment]
> That worked, thanks! As I have no idea which components communicate with each other on HTTP or HTTPS (obviously Synapse and Solr), I just did the following in docker-compose.yml:
> 
> ```
> x-common-variables: &common-variables
>   http_proxy: REDADCTED
>   https_proxy: REDACTED
>   no_proxy: docintel-dev-synapse,docintel-dev-source-indexer,docintel-dev-rabbitmq,docintel-dev-document-indexer,docintel-dev-tag-indexer,docintel-dev-thumbnailer,docintel-dev-solr
> 
> services:
> ...
>         environment: *common-variables
> ...
>   synapse:
>     environment:
>       <<: *common-variables
>       SYN_CORTEX_AUTH_PASSWD: REDACTED
> ```
> 
> And that works. However, all RSS-imported documents are still pending ingestion and nothing happens. Could you direct me in which containers I need to put on the no_proxy list for DocIntel to work completely?
> 
> Thanks again for your help! I already saw the ticket you made to improve documentation. :)

Hello,

Could you please share your new docker-compose.yml ? I don't know where to add these lines
