### ISSUE TITLE
Services won't restart after creating a new role

### ISSUE THREAD

**Issue by nicocti** [docintelapp/DocIntel#8]
Hello,

Thanks for your amazing work on this new tool 👏 

I encounter a bug when playing with the auhorization features. Services won't initialize when restarted after creating a new role. The following exception is raised:

```
Unhandled exception. System.InvalidOperationException: Sequence contains more than one element.
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at DocIntel.Core.Services.BaseDataDbService.ApplyYourChangeAsync(IServiceProvider scopedServices) in /src/DocIntel.Core/Services/BaseDataDbService.cs:line 57
   at RunMethodsSequentially.LockAndRunCode.JobRunner.RunJobAsync(IServiceProvider scopedServices)
   at RunMethodsSequentially.LockAndRunCode.PostgreSqlLockAndRunJob.LockAndRunMethodsAsync(IServiceProvider serviceProvider)
   at RunMethodsSequentially.LockAndRunCode.PostgreSqlLockAndRunJob.LockAndRunMethodsAsync(IServiceProvider serviceProvider)
   at RunMethodsSequentially.LockAndRunCode.GetLockAndThenRunServices.LockAndLoadAsync()
   at RunMethodsSequentially.LockAndRunCode.GetLockAndThenRunHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at DocIntel.Services.Thumbnailer.Program.Main(String[] args) in /src/DocIntel.Services.Thumbnailer/Program.cs:line 33
```

To reproduce the issue:

1. Start the platform using `run.sh`
2. Create a new "Role"
3. Docker restart one of the microservices

**Comment by ancailliau** [comment]
Thanks for the report. I'm amazed that I never encountered that one :-)

**Comment by nicocti** [comment]
Top ! Do you plan to rebuild the docker images with the fix before the next release ?
