### ISSUE TITLE
Missing field suggest_title

### ISSUE THREAD

**Issue by ancailliau** [docintelapp/DocIntel#81]
```
2023-07-03 09:57:14.8402 [ERROR] [DocIntel.Core.Utils.Search.Tags.SolrFacetSearchEngine] The remote server returned an error: (400) Bad Request.
2023-07-03 09:57:14.8402 [ERROR] [DocIntel.Core.Utils.Search.Tags.SolrFacetSearchEngine] [null]
2023-07-03 09:57:14.8402 [WARN] [DocIntel.Core.Utils.Search.Tags.SolrFacetSearchEngine]    at SolrNet.Impl.PostSolrConnection.Get(String relativeUrl, IEnumerable`1 parameters)
   at SolrNet.Impl.AutoSolrConnection.Get(String relativeUrl, IEnumerable`1 parameters)
   at SolrNet.Impl.SolrQueryExecuter`1.Execute(ISolrQuery q, QueryOptions options)
   at SolrNet.Impl.SolrBasicServer`1.Query(ISolrQuery query, QueryOptions options)
   at SolrNet.Impl.SolrServer`1.Query(ISolrQuery query, QueryOptions options)
   at DocIntel.Core.Utils.Search.Tags.SolrFacetSearchEngine.Suggest(TagFacetSearchQuery query) in /src/DocIntel.Core/Utils/Search/Tags/SolrFacetSearchEngine.cs:line 131
2023-07-03 09:57:14.8536 [WARN] [DocIntel.Core.Utils.Search.Tags.SolrFacetSearchEngine] <?xml version="1.0" encoding="UTF-8"?>
<response>
<lst name="responseHeader"><int name="status">400</int><int name="QTime">77</int></lst><lst name="error"><lst name="metadata"><str name="error-class">org.apache.solr.common.SolrException</str><str name="root-error-class">org.apache.solr.common.SolrException</str></lst><str name="msg">org.apache.solr.search.SyntaxError: Query Field 'suggest_title' is not a valid field name</str><int name="code">400</int></lst>
</response>

```

**Comment by ancailliau** [comment]
You should re-index your facets after upgrading to the latest version 

```
docker exec -it docintel-webapp /cli/DocIntel.AdminConsole index facets
```
